# List of project configurations
CONFIGS = [
    {
        "BRANCH": 'origin/main',
        "REPO_PATH": 'C:\\_Work\\krutoblin',
        "ITCH_PROJECT": 'sangheli/krutoblin:webgl',
        "UNITY_EXECUTABLE": '"C:\\Program Files\\Unity\\Hub\\Editor\\6000.1.0f1\\Editor\\Unity.exe"',
        "BUILD_PATH": 'C:\\_Work\\krutoblin\\webgl_build',
        "UNITY_BUILD_METHOD": "WebGLBuilder.Build",
        "BUILD_TARGET": "WebGL",
        "UPLOAD": True,
        "FORCE": True,
    },
    {
        "BRANCH": 'origin/main',
        "REPO_PATH": 'C:\\_Work\\RedBall',
        "UNITY_EXECUTABLE": '"C:\\Program Files\\Unity\\Hub\\Editor\\6000.1.0f1\\Editor\\Unity.exe"',
        "BUILD_PATH": 'C:\\_Work\\RedBall\\androidBuild',
        "UNITY_BUILD_METHOD": "AndroidBuilder.Build",
        "BUILD_TARGET": "Android",
        "FORCE": True,
        "UPLOAD":False,
    },
    {
        "BRANCH": 'origin/main',
        "REPO_PATH": 'C:\\_Work\\PaperShooter',
        "ITCH_PROJECT": 'sangheli/papershooter:webgl',
        "UNITY_EXECUTABLE": '"C:\\Program Files\\Unity\\Hub\\Editor\\6000.1.0f1\\Editor\\Unity.exe"',
        "BUILD_PATH": 'C:\\_Work\\PaperShooter\\webgl_build',
        "UNITY_BUILD_METHOD": "WebGLBuilder.Build",
        "BUILD_TARGET": "WebGL",
        "FORCE": True,
        "UPLOAD": True,
    },
    {
        "BRANCH": 'origin/update3',
        "REPO_PATH": 'C:\\_Work\\HellDigger-Web',
        "ITCH_PROJECT": 'sangheli/ld57helldiggeridle:webgl',
        "UNITY_EXECUTABLE": '"C:\\Program Files\\Unity\\Hub\\Editor\\6000.1.0f1\\Editor\\Unity.exe"',
        "BUILD_PATH": 'C:\\_Work\\HellDigger-Web\\webgl_build',
        "UNITY_BUILD_METHOD": "WebGLBuilder.Build",
        "BUILD_TARGET": "WebGL",
        "FORCE": True,
        "UPLOAD": True,
    },
    {
        "BRANCH": 'origin/stachka2025',
        "REPO_PATH": 'C:\\_Work\\minitank-web',
        "ITCH_PROJECT": 'sangheli/minitankdesertstrikedemo1:webgl',
        "UNITY_EXECUTABLE": '"C:\\Program Files\\Unity\\Hub\\Editor\\6000.1.0f1\\Editor\\Unity.exe"',
        "BUILD_PATH": 'C:\\_Work\\minitank-web\\webgl_build',
        "UNITY_BUILD_METHOD": "WebGLBuilder.Build",
        "BUILD_TARGET": "WebGL",
        "FORCE": False,
        "UPLOAD": True,
    },
    {
        "BRANCH": 'origin/main',
        "REPO_PATH": 'C:\\_Work\\sibjam2025-web',
        "ITCH_PROJECT": 'sangheli/towerascend-postjam:webgl',
        "UNITY_EXECUTABLE": '"C:\\Program Files\\Unity\\Hub\\Editor\\6000.1.0f1\\Editor\\Unity.exe"',
        "BUILD_PATH": 'C:\\_Work\\sibjam2025-web\\webgl_build',
        "UNITY_BUILD_METHOD": "WebGLBuilder.Build",
        "BUILD_TARGET": "WebGL",
        "FORCE": True,
        "UPLOAD": True,
    },
    {
        "BRANCH": 'origin/main',
        "REPO_PATH": 'C:\\_Work\\ZombieHealer',
        "ITCH_PROJECT": 'sangheli/zombiehealer:webgl',
        "UNITY_EXECUTABLE": '"C:\\Program Files\\Unity\\Hub\\Editor\\6000.2.0a10\\Editor\\Unity.exe"',
        "BUILD_PATH": 'C:\\_Work\\ZombieHealer\\webgl_build',
        "UNITY_BUILD_METHOD": "WebGLBuilder.Build",
        "BUILD_TARGET": "WebGL",
        "FORCE": True,
        "UPLOAD": True,
    },
]