# List of project configurations
CONFIGS = [
    {
        "BRANCH": 'origin/main',
        "REPO_PATH": 'C:\\_Work\\krutoblin',
        "ITCH_PROJECT": 'sangheli/krutoblin:webgl',
        "UNITY_EXECUTABLE": '"C:\\Program Files\\Unity\\Hub\\Editor\\6000.1.0f1\\Editor\\Unity.exe"',
        "BUILD_PATH": 'C:\\_Work\\krutoblin\\webgl_build',
        "UNITY_BUILD_METHOD": "WebGLBuilder.Build",
        "BUILD_TARGET": "WebGL",
        "UPLOAD": True,
        "FORCE": True,
    },
    {
        "BRANCH": 'origin/main',
        "REPO_PATH": 'C:\\_Work\\RedBall',
        "UNITY_EXECUTABLE": '"C:\\Program Files\\Unity\\Hub\\Editor\\6000.1.0f1\\Editor\\Unity.exe"',
        "BUILD_PATH": 'C:\\_Work\\RedBall\\androidBuild',
        "UNITY_BUILD_METHOD": "AndroidBuilder.Build",
        "BUILD_TARGET": "Android",
        "FORCE": True,
        "UPLOAD":False,
    },
    {
        "BRANCH": 'origin/main',
        "REPO_PATH": 'C:\\_Work\\PaperShooter',
        "ITCH_PROJECT": 'sangheli/papershooter:webgl',
        "UNITY_EXECUTABLE": '"C:\\Program Files\\Unity\\Hub\\Editor\\6000.1.0f1\\Editor\\Unity.exe"',
        "BUILD_PATH": 'C:\\_Work\\PaperShooter\\webgl_build',
        "UNITY_BUILD_METHOD": "WebGLBuilder.Build",
        "BUILD_TARGET": "WebGL",
        "FORCE": True,
        "UPLOAD": True,
    },
    {
        "BRANCH": 'origin/update3',
        "REPO_PATH": 'C:\\_Work\\hellDigger',
        "ITCH_PROJECT": 'sangheli/ld57helldiggeridle:webgl',
        "UNITY_EXECUTABLE": '"C:\\Program Files\\Unity\\Hub\\Editor\\6000.2.0a10\\Editor\\Unity.exe"',
        "BUILD_PATH": 'C:\\_Work\\hellDigger\\webgl_build',
        "UNITY_BUILD_METHOD": "WebGLBuilder.Build",
        "BUILD_TARGET": "WebGL",
        "FORCE": True,
        "UPLOAD": True,
    },
    {
        "BRANCH": 'origin/stachka2025',
        "REPO_PATH": 'C:\\_Work\\minitank-web',
        "ITCH_PROJECT": 'sangheli/minitankdesertstrikedemo1:webgl',
        "UNITY_EXECUTABLE": '"C:\\Program Files\\Unity\\Hub\\Editor\\6000.1.0f1\\Editor\\Unity.exe"',
        "BUILD_PATH": 'C:\\_Work\\minitank-web\\webgl_build',
        "UNITY_BUILD_METHOD": "WebGLBuilder.Build",
        "BUILD_TARGET": "WebGL",
        "FORCE": False,
        "UPLOAD": True,
    },
    {
        "BRANCH": 'origin/main',
        "REPO_PATH": 'C:\\_Work\\sibjam2025-web',
        "ITCH_PROJECT": 'sangheli/towerascend-postjam:webgl',
        "UNITY_EXECUTABLE": '"C:\\Program Files\\Unity\\Hub\\Editor\\6000.1.0f1\\Editor\\Unity.exe"',
        "BUILD_PATH": 'C:\\_Work\\sibjam2025-web\\webgl_build',
        "UNITY_BUILD_METHOD": "WebGLBuilder.Build",
        "BUILD_TARGET": "WebGL",
        "FORCE": True,
        "UPLOAD": True,
    },
    {
        "BRANCH": 'origin/main',
        "REPO_PATH": 'C:\\_Work\\ZombieHealer',
        "ITCH_PROJECT": 'sangheli/zombiehealer:webgl',
        "UNITY_EXECUTABLE": '"C:\\Program Files\\Unity\\Hub\\Editor\\6000.2.0a10\\Editor\\Unity.exe"',
        "BUILD_PATH": 'C:\\_Work\\ZombieHealer\\webgl_build',
        "UNITY_BUILD_METHOD": "WebGLBuilder.Build",
        "BUILD_TARGET": "WebGL",
        "FORCE": True,
        "UPLOAD": True,
    },
    {
        "BRANCH": 'origin/main',
        "REPO_PATH": 'C:\\_Work\\PotatoKing',
        "ITCH_PROJECT": 'sangheli/potatoking-farming-idle-simulator:webgl',
        "UNITY_EXECUTABLE": '"C:\\Program Files\\Unity\\Hub\\Editor\\6000.2.0a10\\Editor\\Unity.exe"',
        "BUILD_PATH": 'C:\\_Work\\PotatoKing\\webgl_build',
        "UNITY_BUILD_METHOD": "WebGLBuilder.Build",
        "BUILD_TARGET": "WebGL",
        "FORCE": True,
        "UPLOAD": True,
    },
    {
        "BRANCH": 'origin/main',
        "REPO_PATH": 'C:\\_Work\\wasdjam25',
        "ITCH_PROJECT": 'sangheli/mainframe-fantasy:webgl',
        "UNITY_EXECUTABLE": '"C:\\Program Files\\Unity\\Hub\\Editor\\6000.2.0b1\\Editor\\Unity.exe"',
        "BUILD_PATH": 'C:\\_Work\\wasdjam25\\webgl_build',
        "UNITY_BUILD_METHOD": "WebGLBuilder.Build",
        "BUILD_TARGET": "WebGL",
        "FORCE": True,
        "UPLOAD": True,
    },
    {
        "BRANCH": 'origin/main',
        "REPO_PATH": 'C:\\_Work\\circle_idle',
        "ITCH_PROJECT": 'sangheli/circleidle:win',
        "UNITY_EXECUTABLE": '"C:\\Program Files\\Unity\\Hub\\Editor\\6000.2.0b3\\Editor\\Unity.exe"',
        "BUILD_PATH": 'C:\\_Work\\circle_idle\\pc_build',
        "UNITY_BUILD_METHOD": "WinBuilder.Build",
        "BUILD_TARGET": "Win64",
        "FORCE": True,
        "UPLOAD": True,
        "NO_GIT": True,  # <<< Добавь сюда, если хочешь выключить работу с гитом,
        "ZIP_BEFORE_UPLOAD": True, #for win builds
    },
    {
        "BRANCH": 'origin/main',
        "REPO_PATH": 'C:\\_Work\\circle_idle',
        "ITCH_PROJECT": 'sangheli/circleidle:linux',
        "UNITY_EXECUTABLE": '"C:\\Program Files\\Unity\\Hub\\Editor\\6000.2.0b3\\Editor\\Unity.exe"',
        "BUILD_PATH": 'C:\\_Work\\circle_idle\\linux_build',
        "UNITY_BUILD_METHOD": "LinuxBuilder.Build",
        "BUILD_TARGET": "Linux64",
        "FORCE": True,
        "UPLOAD": True,
        "NO_GIT": True,  # <<< Добавь сюда, если хочешь выключить работу с гитом,
        "ZIP_BEFORE_UPLOAD": True,  # for win builds
    },
    {
        "BRANCH": 'origin/main',
        "REPO_PATH": 'C:\\_Work\\circle_idle',
        "ITCH_PROJECT": 'sangheli/circleidle:mac',
        "UNITY_EXECUTABLE": '"C:\\Program Files\\Unity\\Hub\\Editor\\6000.2.0b3\\Editor\\Unity.exe"',
        "BUILD_PATH": 'C:\\_Work\\circle_idle\\mac_build',
        "UNITY_BUILD_METHOD": "MacBuilder.Build",
        "BUILD_TARGET": "OSX",
        "FORCE": True,
        "UPLOAD": True,
        "NO_GIT": True,  # <<< Добавь сюда, если хочешь выключить работу с гитом,
        "ZIP_BEFORE_UPLOAD": True,  # for win builds
    },
    {
        "BRANCH": 'origin/main',
        "REPO_PATH": 'C:\\_Work\\circle_idle',
        "ITCH_PROJECT": 'sangheli/circleidle:android',
        "UNITY_EXECUTABLE": '"C:\\Program Files\\Unity\\Hub\\Editor\\6000.2.0b3\\Editor\\Unity.exe"',
        "BUILD_PATH": 'C:\\_Work\\circle_idle\\androidBuild',
        "UNITY_BUILD_METHOD": "AndroidBuilder.Build",
        "BUILD_TARGET": "Android",
        "FORCE": True,
        "UPLOAD": True,
        "NO_GIT": True,  # <<< Добавь сюда, если хочешь выключить работу с гитом,
        "ZIP_BEFORE_UPLOAD": False,  # for win builds
        "UPLOAD_TELEGRAM": False,
        "UPLOAD_DROPBOX": False,
        "TELEGRAM_BOT_TOKEN": "",
        "TELEGRAM_CHAT_ID": "",
        "DROPBOX_PATH": "C:\\Dropbox\\Public",
        "ZIP_METHOD": "7z",  # zip или 7z
    },
]